name: Scheduled check for new sky photo

on:
  schedule:
    # Run daily ~10:10am EST
    - cron: "10 15 * * *"
  # Run the workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  update-sky-photos:
      runs-on: ubuntu-latest
      steps:
        - name: Check out repo
          uses: actions/checkout@v6
        - name: Install deps
          uses: bahmutov/npm-install@v1
          with:
            working-directory: skies
            useLockFile: false
        - name: Run script
          id: run-script
          working-directory: skies
          env:
              TUMBLR_BLOG: ${{ secrets.TUMBLR_BLOG }}
              TUMBLR_CONSUMER_KEY: ${{ secrets.TUMBLR_CONSUMER_KEY }}
              TUMBLR_SECRET_KEY: ${{ secrets.TUMBLR_SECRET_KEY }}
              TUMBLR_OATH_TOKEN: ${{ secrets.TUMBLR_OATH_TOKEN }}
              TUMBLR_OATH_TOKEN_SECRET: ${{ secrets.TUMBLR_OATH_TOKEN_SECRET }}
          run: node skies.js
        - name: Check output
          run: echo "Missing photos -> ${{ steps.run-script.outputs.missing-photos }}"
        - name: Copy JSON file
          if: steps.run-script.outputs.missing-photos > 0
          run: cp skies/temp-sky.json src/_data/sky.json
        - name: Commit changes
          uses: stefanzweifel/git-auto-commit-action@v4
          if: steps.run-script.outputs.missing-photos > 0
          with:
            commit_message: "Automagically add latest sky photos"
            commit_user_name: "Update Skies GH Action"
